### ISSUE TITLE
Custom delimeters

### ISSUE THREAD

**Issue by ftuyama** [mechatroner/sublime_rainbow_csv#1]
Hey there!

I would like to improve the project adding a custom delimeter setting to the project. What do you think about the idea?

**Comment by mechatroner** [comment]
Hello!
I planned to do this myself sometime in the future, but if you want to help, you can go ahead and code this :)
But I want this to be done in a similar way as it is implemented in Vim version of rainbow_csv:
1)  In order to choose a custom delimiter for the current file user will have to select it with mouse, right click, and choose either "quoted rainbow delimiter" or "simple rainbow delimiter"  from the context menu to highlight the current file.
2) Selection from step 1 will be stored in session-persistent manner, so user will not have to choose again for the same file
3) User can cancel rainbow highlighting (original syntax before applying rainbow highigting should be restored) and this decision erase entry from that session-persistent storage. 
Does this UI sound reasonable?

BTW each possible delimiter will require creation of two syntax files - quoted and non-quoted versions, you will have to generate them using tsv and csv syntaxes as templates.

So, what do you think?

**Comment by mechatroner** [comment]
Done
