### ISSUE TITLE
The order of colors and a bug with a comma

### ISSUE THREAD

**Issue by john-cj** [mechatroner/sublime_rainbow_csv#31]
It seems to me that the order of colors is somewhat random. I don't know is it a bug or by intent, but I would prefer a more predictable order. For example: red, green, blue, violet, red, green, blue, violet, red, green, blue, violet, and so on.

![image](https://user-images.githubusercontent.com/18004961/110204787-08020680-7e86-11eb-9650-6085c379b9c1.png)

Also, it seems there is a bug with a comma: notice that a comma before 8, 11, 18, and 21 should be white.

Tested with Mariana default color scheme.

**Comment by mechatroner** [comment]
Thanks for spotting this bug, @john-cj ! I know what the root cause is, and trying to find how to fix it with minimal fallout (basically the scope names for columns 10 * n + 1 and 10 * n + 8 don't exist in the default color scheme, this causes it to fall back to the default color, but the matching rules made in a way that the previous group also captures the separator, and if the next group has a scope color defined it overwrites the previous scope color, but otherwise the separators remains colored by the previous group color) 
You can actually fix the bug and have nice your own nice custom colors by setting `use_custom_rainbow_colors` and optionally `auto_adjust_rainbow_colors`. If you just set `use_custom_rainbow_colors` you should theoretically be able to customize the colors as you like, see the README file. You can use this file as a template for your own custom colors: https://github.com/mechatroner/sublime_rainbow_csv/blob/master/RainbowCSV.sublime-color-scheme

**Comment by john-cj** [comment]
Thanks, I will look it today.

**Comment by mechatroner** [comment]
One solution is to replace `meta_scope` with `meta_content_scope` in all syntax rules - this will group columns with trailing separators instead of preceding (just like in VSCode version) - but in that case, the internal python offset calculation logic will have to be adjusted too. Just thinking out loud.

**Comment by mechatroner** [comment]
I just released version 2.4.0 that should fix the comma bug.

**Comment by Huntk23** [comment]
Using `2.7.0` - I still seem to have a similar issue:

![image](https://user-images.githubusercontent.com/3951241/162058930-02d9b042-6b13-437c-90a5-86296a6725a9.png)

I've also attempted to use `use_custom_rainbow_colors` but not quite understanding the rules.
